[MeterShadowBar0]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar1]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar2]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar3]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar4]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar5]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar6]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar7]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar8]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar9]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar10]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar11]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar12]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed12
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar13]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed13
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar14]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed14
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar15]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed15
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar16]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed16
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar17]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed17
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar18]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed18
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar19]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed19
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)